/**
 * This package contains classes auto-generated by Hapi tinder plugin and modified to suit the capabilities of
 * this jpa-server implementation.
 * 
 * @see https://github.com/jamesagnew/hapi-fhir/tree/master/hapi-tinder-plugin
 * @author Ismael Sarmento
 */
package edu.gatech.i3l.fhir.jpa.providers;